#!/bin/bash
echo -e " this is a first line \n this is second line "
echo -n "this is one more line"
echo "this is second line"
echo -e " this is a first line \b this is sec line "
echo -e " this is a first line \t this is fourt line "
echo -e " this is a first line \v this is second line "
echo -e " this is a first line \a this is second line "
echo -e " this is a first line \r this is second line "
echo -e " this is a first line \c this is second line "
echo -e " this is a first line \\ this is second line "
