#!/bin/bash
#req_tom_ver=$1
read -p" required tomacat version: " req_tom_ver
tom_main_ver=$(echo $req_tom_ver|cut -c 1)
url="https://dlcdn.apache.org/tomcat/tomcat-${tom_main_ver}/v${req_tom_ver}/bin/apache-tomcat-${req_tom_ver}.tar.gz"
wget $url
tar -xvzf apache-tomcat-${req_tom_ver}.tar.gz
mv apache-tomcat-${req_tom_ver} tomcat ${tom_main_ver}
rm -rf apache-tomcat-${req_tom_ver}.tar.gz

